### ISSUE TITLE
一些使用体验，感谢up主哈哈哈

### ISSUE THREAD

**Issue by WhySRZ** [zerochl/ClassicDownload#3]
**我的项目在用了，还是不错的，不过还有些小问题像Pull request里说的count的问题，然后在存储路径自定义CDownloadConfig.build().setDiskCachePath时，三星的手机有时会出现自定义缓存路径失效，最后我把自定义缓存的路径直接写到缓存路径默认值那去多了层保险，所以我用的时候直接下载了library包，用的文件名默认是下载地址，这个也值得注意，如果想自定义文件名，我是在CDownloadTaskEntity加了个FileName,在CDownload的create（）方法把fileName传进来，（就是调用这个方法时CDownload.getInstance().create将文件名当参数传进来）然后在FileManager的PathUtil.getLocalFilePath、PathUtil.getLocalFilePath获取文件名生成指定文件名文件。**

**Comment by zerochl** [comment]
项目可以一起开发，欢迎提交PullRequest
