### ISSUE TITLE
如果下载中APP进程被杀死，如果在重新打开应用，接着断开的进度继续下载

### ISSUE THREAD

**Issue by AutumnLeavesss** [zerochl/ClassicDownload#4]
您好！如果下载中APP进程被杀死，如果在重新打开应用，接着断开的进度继续下载

**Comment by zerochl** [comment]
本库是有断点续传的，但是你说的这个自动接着开始下载本库暂时还不支持，而且这种支持应该属于更上层的管理，当然下载库提供某种设置也是可以的，我会考虑这件事情的。
